// examples/vue/src/App.vue
<script setup lang="ts">
// always import @brand, no need to know which brand is active
import Banner from "@brand-components/Banner.vue";
import Footer from "@brand-components/Footer.vue";

const mode = DEV ? "development" : "production";
</script>

<template>
  <main>
    <Banner />
    <p>Framework: Vue</p>
    <p>Vite mode: {{ mode }}</p>
    <Footer />
  </main>
</template>

// examples/react/src/App.tsx
import Banner from "@brand-components/Banner";
import Footer from "@brand-components/Footer";

const mode = DEV ? "development" : "production";

export default function App() {
  return (
    <main>
      <Banner />
      <p>Framework: React</p>
      <p>Vite mode: {mode}</p>
      <Footer />
    </main>
  );
}
